#  spring.cloud.config.discovery.enabled 是从配置中心读取文件。
#  spring.cloud.config.discovery.serviceId 配置中心的servieId（config-server），即服务名；

spring:
  application:
    name: config-client
  cloud:
    config:
      #uri: http://localhost:9102
      name: config-demo
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/


